export const FETCH_CITY_LOADING = "FETCH_CITY_LOADING"
export const FETCH_CITY_ERROR = "FETCH_CITY_ERROR"
export const FETCH_CITY_SUCCESS = "FETCH_CITY_SUCCESS"

export const REMOVE_CITY = "REMOVE_CITY"
