export const FETCH_CITY_LOADING = "FETCH_CITY_LOADING"
export const FETCH_CITY_ERROR = "FETCH_CITY_ERROR"
export const FETCH_CITY_SUCCESS = "FETCH_CITY_SUCCESS"

export const ADD_FAVORITE = "ADD_FAVORITE"
export const REMOVE_FAVORITE = "REMOVE_FAVORITE"
export const FETCH_FAVORITES = "FETCH_FAVORITES"
